---
title: Mes GameObjects se traversent
hero_image: images/banner.png
description: Mes GameObjects se traversent
version: 4
listed: false
copyedit: false
last_tested: "2021-11-23"
steps:
  - title: Mes GameObjects se traversent
